management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 5555

  #Setting logging levels
logging:
    level:
      com.netflix: WARN
      org.springframework.web: DEBUG
      com.thoughtmechanix: DEBUG

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:        defaultZone: http://localhost:8761/eureka/

zuul:
  prefix: /api
  sensitive-headers:  - Cookie
  - Set-Cookie